### ISSUE TITLE
v6 patches are out

### ISSUE THREAD

**Issue by joske** [ubenmackin/ACVM#29]
Hi,

I just noticed the v6 patches are available. I hope you get to integrate them before my macbook air arrives in 2 weeks :-D

**Comment by ubenmackin** [comment]
@joske I'll work on this tonight or tomorrow.

**Comment by ubenmackin** [comment]
So it looks like something has changed, because when I pull down the latest qemu sources, and the v6 patch and applied them, the virtio-gpu device no longer works:

qemu-system-aarch64: -device virtio-gpu: 'virtio-gpu' (alias 'virtio-gpu-pci') is not a valid device model name

I'll try and do some more digging and see if I can see what is going on.

**Comment by joske** [comment]
Hmm, strange. Sorry can't yet help, I only have 2 hackintoshes (so intel ;-)). Was trying to see if I could already help by running it in x86, but as you know, can't get it to run.

**Comment by joske** [comment]
There's an extra patch now:
https://patchwork.kernel.org/project/qemu-devel/list/?submitter=185121

My macbook air should arrive Monday :-).

**Comment by joske** [comment]
Macbook arrived, I was able to compile qemu with the v6 patches, and it works perfectly with virtio-gpu-pci (via commandline not via ACVM, as I can't compile ACVM yet).

**Comment by ubenmackin** [comment]
Interesting, wonder what I did wrong.

would you mind sharing the steps you took to apply the patch and compile the code base for qemu? I can give it another shot.

**Comment by joske** [comment]
See my pull request, I've already built them.

I did like this:

- clone https://github.com/patchew-project/qemu.git
- checkout the tag with the patchset patchew/20210120224444.71840-1-agraf@csgraf.de
- created a local branch for it (optional, but I don't like detached head ;-))
- followed standard qemu build procedure

**Comment by ubenmackin** [comment]
Oh, interesting you're using a different repo that I was. I was using

https://github.com/qemu/qemu

And actually I just did a fresh clone from there, and the patch didn't apply. Looking at things, it appears these have now been applied to the main repo as of 14 days ago.

But I'm having a problem building this now, it is throwing some errors on build. I think it might be my Xcode is out of date for my OS (I'm running 11.3 beta). I'll get everything patched up and try again.

**Comment by ubenmackin** [comment]
> * clone https://github.com/patchew-project/qemu.git
> * checkout the tag with the patchset patchew/20210120224444.71840-1-agraf@csgraf.de
> * created a local branch for it (optional, but I don't like detached head ;-))
> * followed standard qemu build procedure

So I must be missing something on my ./configure because when I am building, again it is complaining about virtio-gpu.

`qemu-system-aarch64: -device virtio-gpu: 'virtio-gpu' (alias 'virtio-gpu-pci') is not a valid device model name`

Here is my ./configure command:

`./configure --cpu=aarch64 --target-list=aarch64-softmmu --smbd=/usr/sbin/smbd --enable-libusb --enable-modules --enable-guest-agent --enable-tools --enable-hvf`

I swear this worked before, and got me a binary that worked with virtio-gpu. Can you share your command?

**Comment by joske** [comment]
I did not pass any arguments to ./configure. Then I just ran make.

The other github project automatically has tags for all patch sets in patchwork. Very handy, no manual patch applying.
